---
# Ansible Galaxy Collections Requirements
# This file specifies all Ansible collections needed for the Cloud Resume Challenge playbooks
#
# Installation:
#   ansible-galaxy collection install -r requirements.yml
#
# Upgrade to latest versions:
#   ansible-galaxy collection install -r requirements.yml --upgrade
#
# Force reinstall:
#   ansible-galaxy collection install -r requirements.yml --force

collections:
  # Amazon AWS Collection
  # Core AWS modules for CloudFormation, S3, EC2, IAM, etc.
  # Documentation: https://docs.ansible.com/ansible/latest/collections/amazon/aws/
  - name: amazon.aws
    version: ">=8.0.0"
    source: https://galaxy.ansible.com

  # Community AWS Collection
  # Extended AWS modules including S3 sync, lifecycle policies, etc.
  # Documentation: https://docs.ansible.com/ansible/latest/collections/community/aws/
  - name: community.aws
    version: ">=8.0.0"
    source: https://galaxy.ansible.com

  # Community General Collection (optional but useful)
  # Provides general-purpose modules for various tasks
  # Documentation: https://docs.ansible.com/ansible/latest/collections/community/general/
  - name: community.general
    version: ">=9.0.0"
    source: https://galaxy.ansible.com
